# PostgreSQL DataSource Configuration (Connecting to Docker Container)
# CORREGIDO: Ajustado para coincidir con los parámetros de Docker.
spring.datasource.url=jdbc:postgresql://localhost:5432/gestion_seguridad_aeroportuaria
spring.datasource.username=salva
spring.datasource.password=2020

# JPA/Hibernate Configuration
# 'update' es útil para desarrollo, pero para producción se recomienda 'validate' o una herramienta de migración como Flyway/Liquibase.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Vaadin Configuration
# Asegura que Vaadin no redirija a /login si ya estamos en la página de login, evitando bucles.
vaadin.urlMapping=/

# ===============================================
# CONFIGURACIÓN DEL SERVIDOR DE CORREO (GMAIL)
# ===============================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=aero.sec2025@gmail.com
spring.mail.password=usyk esbl ughg bfek
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true